version: '3'
services:
  backend-scm:
    image: 'backend-scm:latest'
    ports:
      - '3030:3030'
  backend-user:
    image: 'backend-user:latest'
    ports:
      - '3020:3020'
  frontend:
    image: 'frontend:latest'
    ports:
      - '80:80'
